// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNCoxakfPQOjAAH3xHJKCFCQhR2UIYmV0',
    appId: '1:940718977696:web:8c0527d6e037d39addcfc5',
    messagingSenderId: '940718977696',
    projectId: 'medical-12bec',
    authDomain: 'medical-12bec.firebaseapp.com',
    storageBucket: 'medical-12bec.firebasestorage.app',
    measurementId: 'G-F55VGXERSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-PklWTBzuvSQzAzt9l6zcUp4jrDMzPnk',
    appId: '1:940718977696:android:2589f04f6b882d72ddcfc5',
    messagingSenderId: '940718977696',
    projectId: 'medical-12bec',
    storageBucket: 'medical-12bec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Pc6vGbeORwuBWiIOemVLVNQ0HQiE4Rs',
    appId: '1:940718977696:ios:8f3d8e67917027d0ddcfc5',
    messagingSenderId: '940718977696',
    projectId: 'medical-12bec',
    storageBucket: 'medical-12bec.firebasestorage.app',
    androidClientId: '940718977696-mc26ct8bt66dk8dpkblg0k9p7ijin79s.apps.googleusercontent.com',
    iosClientId: '940718977696-anmsjjlhuphf97grlkd51mu31b63rsoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gfhfg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Pc6vGbeORwuBWiIOemVLVNQ0HQiE4Rs',
    appId: '1:940718977696:ios:8f3d8e67917027d0ddcfc5',
    messagingSenderId: '940718977696',
    projectId: 'medical-12bec',
    storageBucket: 'medical-12bec.firebasestorage.app',
    androidClientId: '940718977696-mc26ct8bt66dk8dpkblg0k9p7ijin79s.apps.googleusercontent.com',
    iosClientId: '940718977696-anmsjjlhuphf97grlkd51mu31b63rsoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gfhfg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNCoxakfPQOjAAH3xHJKCFCQhR2UIYmV0',
    appId: '1:940718977696:web:b32f76f2efe59bc1ddcfc5',
    messagingSenderId: '940718977696',
    projectId: 'medical-12bec',
    authDomain: 'medical-12bec.firebaseapp.com',
    storageBucket: 'medical-12bec.firebasestorage.app',
    measurementId: 'G-1W7MJR5ZRT',
  );
}
